[project]
name = "stupid-movie-trailer-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "requests",
    "streamlit",
    "audiostretchy",
    "python-ffmpeg",
    "moviepy",
    "pydub",
]

[tool.uv]
dev-dependencies = []
