/**
 * Caption building for the Instagram-ready trailer video.
 *
 * The voiceover is generated by ElevenLabs without word-level timestamps, so
 * caption timings are approximated by distributing the total voiceover
 * duration across caption chunks proportionally to their word count.
 */

export interface Caption {
  text: string
  /** Start time in seconds (inclusive). */
  start: number
  /** End time in seconds (exclusive). */
  end: number
}

/**
 * Extracts narrator voiceover lines from a movie script.
 * Also used by `extractNarratorText` to keep legacy narration extraction consistent.
 * @param {string} script - The movie script text.
 * @returns {string[]} Narrator lines in script order.
 * @example
 * extractNarratorLines('NARRATOR (V.O.)\nIn a world...\n"Only one hero can save them."')
 * // ["In a world...", "Only one hero can save them."]
 */
export function extractNarratorLines(script: string): string[] {
  const lines = script.split("\n")
  const narratorLines: string[] = []

  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim()
    if (trimmed.includes("NARRATOR (V.O.)") || trimmed.includes("NARRATOR (V.O)")) {
      const nextLineIndex = i + 1
      if (nextLineIndex < lines.length) {
        const narratorText = lines[nextLineIndex].trim()
        if (
          narratorText &&
          !narratorText.includes("(") &&
          !narratorText.includes("FADE") &&
          !narratorText.includes("CUT")
        ) {
          narratorLines.push(stripWrappingQuotes(narratorText))
          i = nextLineIndex
        }
      }
    } else if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
      narratorLines.push(trimmed.slice(1, -1))
    }
  }

  return narratorLines
}

function isProductionMarker(line: string): boolean {
  return (
    /^<[^>]*>$/.test(line) ||
    /^(FADE|CUT|DISSOLVE|SMASH CUT|WIPE)\b/i.test(line) ||
    /^[—\-–\s.]*$/.test(line)
  )
}

function stripWrappingQuotes(line: string): string {
  if (line.length > 1 && line.startsWith('"') && line.endsWith('"')) {
    return line.slice(1, -1)
  }
  return line
}

/**
 * Extracts the lines of narration that should get captions from a script.
 * Supports both formats the generator can produce:
 * - Screenplay-style scripts with "NARRATOR (V.O.)" markers and quoted lines.
 * - Pure spoken-text scripts (no markers), where every meaningful line is
 *   narration. Production markers like `<pause>` and `FADE IN:` are dropped.
 * @param {string} script - The movie script text.
 * @returns {string[]} Narration lines in script order.
 * @example
 * extractCaptionLines("They said the internet was forever...\n<pause>\nMEMECEPTION.")
 * // ["They said the internet was forever...", "MEMECEPTION."]
 */
export function extractCaptionLines(script: string): string[] {
  if (/NARRATOR \(V\.O\.?\)/.test(script)) return extractNarratorLines(script)

  const lines: string[] = []
  for (const raw of script.split("\n")) {
    const line = stripWrappingQuotes(raw.trim())
    if (!line || isProductionMarker(line)) continue
    lines.push(line)
  }
  return lines
}

function countWords(text: string): number {
  const words = text.trim().split(/\s+/)
  return words[0] ? words.length : 0
}

/**
 * Splits a line of narration into caption-sized chunks. Sentences are kept
 * intact when short enough; longer sentences are broken into word-count
 * chunks so captions stay readable on a 9:16 video.
 * @param {string} text - A single line of narration.
 * @param {number} maxWords - Maximum number of words per caption chunk.
 * @returns {string[]} Caption chunks in reading order.
 * @example
 * splitIntoCaptionChunks("In a world where peace is a memory. Only one hero can save them.", 6)
 * // ["In a world where peace is", "a memory.", "Only one hero can save them."]
 */
export function splitIntoCaptionChunks(text: string, maxWords: number): string[] {
  const sentences = text
    .split(/(?<=[.!?…])\s+/)
    .map((s) => s.trim())
    .filter(Boolean)

  const chunks: string[] = []
  for (const sentence of sentences) {
    const words = sentence.split(/\s+/)
    if (words.length <= maxWords) {
      chunks.push(sentence)
      continue
    }
    for (let i = 0; i < words.length; i += maxWords) {
      chunks.push(words.slice(i, i + maxWords).join(" "))
    }
  }
  return chunks
}

/**
 * Builds timed captions for the whole narration over the trailer audio.
 * Time is distributed proportionally to word count; each caption stays on
 * screen until the next one begins, and the final caption ends exactly at
 * `duration`.
 * @param {string} script - The movie script text.
 * @param {number} duration - Total audio duration in seconds.
 * @param {number} maxWords - Maximum number of words per caption chunk.
 * @returns {Caption[]} Timed captions, sorted by start time.
 * @example
 * const captions = buildCaptions(script, audioBuffer.duration, 6);
 * // [{ text: "In a world...", start: 0, end: 2.3 }, ...]
 */
export function buildCaptions(script: string, duration: number, maxWords: number = 6): Caption[] {
  if (!(duration > 0) || !(maxWords > 0)) return []

  const chunks = extractCaptionLines(script).flatMap((line) =>
    splitIntoCaptionChunks(line, maxWords),
  )
  const totalWords = chunks.reduce((sum, chunk) => sum + countWords(chunk), 0)
  if (chunks.length === 0 || totalWords === 0) return []

  const captions: Caption[] = []
  let cursor = 0
  for (const chunk of chunks) {
    const span = (countWords(chunk) / totalWords) * duration
    captions.push({ text: chunk, start: cursor, end: cursor + span })
    cursor += span
  }
  captions[captions.length - 1].end = duration
  return captions
}

/**
 * Returns the caption that should be on screen at `time`, or null.
 * @param {Caption[]} captions - Timed captions from `buildCaptions`.
 * @param {number} time - Elapsed time in seconds.
 * @returns {Caption | null} The active caption, or null between/beyond captions.
 * @example
 * const caption = getActiveCaption(captions, 3.2);
 * if (caption) drawCaption(ctx, caption.text);
 */
export function getActiveCaption(captions: Caption[], time: number): Caption | null {
  for (const caption of captions) {
    if (time >= caption.start && time < caption.end) return caption
  }
  const last = captions[captions.length - 1]
  if (last && time === last.end) return null
  return null
}
